In [11]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [12]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]})

In [13]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [14]:
X = df[['temperature_c','sunlight_hours','soil_moisture']]
y = df['needs_water']

In [15]:
X_min = X.min()
X_max = X.max()
X_scaled = ( X - X_min)/( X_max - X_min + 1e-8)

In [16]:
X_scaled

    temperature_c  sunlight_hours  soil_moisture
0          0.9375        0.727273       0.066667
1          0.6875        0.636364       0.133333
2          0.4375        0.545455       0.200000
3          0.1875        0.272727       0.266667
4          0.5625        0.636364       0.466667
5          0.6875        0.818182       0.733333
6          0.0000        0.181818       0.400000
7          0.1875        0.818182       0.173333
8          1.0000        1.000000       0.533333
9          0.3125        0.363636       0.000000
10         0.8750        0.727273       1.000000
11         0.8750        0.909091       0.293333
12         0.1250        0.090909       0.666667
13         0.3750        0.454545       0.866667
14         0.0625        0.000000       0.093333
15         0.6250        0.727273       0.333333

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42,stratify=y)

In [18]:
model = keras.Sequential([
    layers.Input( shape = (X_train.shape[1],)), #input layers
    layers.Dense(8,activation='relu'), #middle hidden layer
    layers.Dense(1,activation='sigmoid') #output layer
])

In [19]:
model.compile(
    optimizer='sgd', #simple gradient descent
    loss='binary_crossentropy',
    metrics = ['accuracy']
    )

In [20]:
history = model.fit(
    X_train.values, y_train.values,
    validation_data =(X_test.values,y_test.values),
    epochs = 100,
    batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 285ms/step - accuracy: 0.6000 - loss: 0.6547 - val_accuracy: 0.8333 - val_loss: 0.6719
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6000 - loss: 0.6527 - val_accuracy: 0.8333 - val_loss: 0.6707
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6000 - loss: 0.6504 - val_accuracy: 0.6667 - val_loss: 0.6695
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.7000 - loss: 0.6489 - val_accuracy: 0.6667 - val_loss: 0.6683
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7000 - loss: 0.6471 - val_accuracy: 0.6667 - val_loss: 0.6673
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.7000 - loss: 0.6464 - val_accuracy: 0.6667 - val_loss: 0.6665
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7000 - loss: 0.6453 - val_accuracy: 0.6667 - val_loss: 0.6660
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7000 - loss: 0.6440 - val_accuracy: 0.6667 - val_loss: 0.6652
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7000 - loss: 0.6423 - val_accuracy: 0.6667 - val_loss: 0.6643
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.7000 - loss: 0.6407 - val_accuracy: 0.6667 - val_loss: 0.6637
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.7000 - loss: 0.6395 - val_accuracy: 0.6667 - val_loss: 0.6632
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 189ms/step - accuracy: 0.7000 - loss: 0.6379 - val_accuracy: 0.6667 - val_loss: 0.6625
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.7000 - loss: 0.6374 - val_accuracy: 0.6667 - val_loss: 0.6615
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 185ms/step - accuracy: 0.8000 - loss: 0.6356 - val_accuracy: 0.6667 - val_loss: 0.6607
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.8000 - loss: 0.6337 - val_accuracy: 0.6667 - val_loss: 0.6599
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 146ms/step - accuracy: 0.9000 - loss: 0.6341 - val_accuracy: 0.6667 - val_loss: 0.6595
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9000 - loss: 0.6308 - val_accuracy: 0.6667 - val_loss: 0.6588
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6304 - val_accuracy: 0.6667 - val_loss: 0.6582
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.6294 - val_accuracy: 0.6667 - val_loss: 0.6578
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.6281 - val_accuracy: 0.6667 - val_loss: 0.6572
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6266 - val_accuracy: 0.6667 - val_loss: 0.6564
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6250 - val_accuracy: 0.6667 - val_loss: 0.6558
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6247 - val_accuracy: 0.6667 - val_loss: 0.6552
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6229 - val_accuracy: 0.6667 - val_loss: 0.6547
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6212 - val_accuracy: 0.6667 - val_loss: 0.6541
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6201 - val_accuracy: 0.6667 - val_loss: 0.6536
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9000 - loss: 0.6198 - val_accuracy: 0.6667 - val_loss: 0.6531
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6192 - val_accuracy: 0.6667 - val_loss: 0.6527
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6179 - val_accuracy: 0.6667 - val_loss: 0.6520
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6167 - val_accuracy: 0.6667 - val_loss: 0.6514
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6147 - val_accuracy: 0.6667 - val_loss: 0.6509
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6148 - val_accuracy: 0.6667 - val_loss: 0.6505
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6139 - val_accuracy: 0.6667 - val_loss: 0.6500
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6129 - val_accuracy: 0.6667 - val_loss: 0.6495
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9000 - loss: 0.6121 - val_accuracy: 0.6667 - val_loss: 0.6491
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6111 - val_accuracy: 0.6667 - val_loss: 0.6484
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.6091 - val_accuracy: 0.6667 - val_loss: 0.6479
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6092 - val_accuracy: 0.6667 - val_loss: 0.6472
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.6077 - val_accuracy: 0.6667 - val_loss: 0.6467
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6088 - val_accuracy: 0.6667 - val_loss: 0.6461
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6051 - val_accuracy: 0.6667 - val_loss: 0.6456
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.6073 - val_accuracy: 0.6667 - val_loss: 0.6450
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.6042 - val_accuracy: 0.6667 - val_loss: 0.6445
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.6024 - val_accuracy: 0.6667 - val_loss: 0.6439
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.6026 - val_accuracy: 0.6667 - val_loss: 0.6433
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9000 - loss: 0.6015 - val_accuracy: 0.6667 - val_loss: 0.6427
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.5995 - val_accuracy: 0.6667 - val_loss: 0.6422
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.5987 - val_accuracy: 0.6667 - val_loss: 0.6417
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9000 - loss: 0.5985 - val_accuracy: 0.6667 - val_loss: 0.6412
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5968 - val_accuracy: 0.6667 - val_loss: 0.6407
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.5963 - val_accuracy: 0.6667 - val_loss: 0.6402
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.5959 - val_accuracy: 0.6667 - val_loss: 0.6398
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.5947 - val_accuracy: 0.6667 - val_loss: 0.6394
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5942 - val_accuracy: 0.6667 - val_loss: 0.6390
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5922 - val_accuracy: 0.6667 - val_loss: 0.6384
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.5914 - val_accuracy: 0.6667 - val_loss: 0.6380
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9000 - loss: 0.5917 - val_accuracy: 0.6667 - val_loss: 0.6376
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9000 - loss: 0.5898 - val_accuracy: 0.6667 - val_loss: 0.6371
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5897 - val_accuracy: 0.6667 - val_loss: 0.6366
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5877 - val_accuracy: 0.6667 - val_loss: 0.6360
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5874 - val_accuracy: 0.6667 - val_loss: 0.6354
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5889 - val_accuracy: 0.6667 - val_loss: 0.6348
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5849 - val_accuracy: 0.6667 - val_loss: 0.6343
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.5848 - val_accuracy: 0.6667 - val_loss: 0.6338
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5831 - val_accuracy: 0.6667 - val_loss: 0.6333
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5832 - val_accuracy: 0.6667 - val_loss: 0.6327
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9000 - loss: 0.5824 - val_accuracy: 0.6667 - val_loss: 0.6324
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5812 - val_accuracy: 0.6667 - val_loss: 0.6319
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.5797 - val_accuracy: 0.6667 - val_loss: 0.6316
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5799 - val_accuracy: 0.6667 - val_loss: 0.6310
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5778 - val_accuracy: 0.6667 - val_loss: 0.6305
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5777 - val_accuracy: 0.6667 - val_loss: 0.6300
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5771 - val_accuracy: 0.6667 - val_loss: 0.6295
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5761 - val_accuracy: 0.6667 - val_loss: 0.6289
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5753 - val_accuracy: 0.6667 - val_loss: 0.6284
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9000 - loss: 0.5735 - val_accuracy: 0.6667 - val_loss: 0.6280
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.5727 - val_accuracy: 0.6667 - val_loss: 0.6275
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9000 - loss: 0.5718 - val_accuracy: 0.6667 - val_loss: 0.6270
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9000 - loss: 0.5708 - val_accuracy: 0.6667 - val_loss: 0.6265
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5699 - val_accuracy: 0.6667 - val_loss: 0.6261
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5691 - val_accuracy: 0.6667 - val_loss: 0.6256
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5693 - val_accuracy: 0.6667 - val_loss: 0.6253
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5685 - val_accuracy: 0.6667 - val_loss: 0.6246
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5664 - val_accuracy: 0.6667 - val_loss: 0.6243
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5657 - val_accuracy: 0.6667 - val_loss: 0.6237
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5655 - val_accuracy: 0.6667 - val_loss: 0.6232
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9000 - loss: 0.5650 - val_accuracy: 0.6667 - val_loss: 0.6227
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5640 - val_accuracy: 0.6667 - val_loss: 0.6221
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5623 - val_accuracy: 0.6667 - val_loss: 0.6216
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5613 - val_accuracy: 0.6667 - val_loss: 0.6212
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5604 - val_accuracy: 0.6667 - val_loss: 0.6207
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5621 - val_accuracy: 0.6667 - val_loss: 0.6202
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5598 - val_accuracy: 0.6667 - val_loss: 0.6197
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5604 - val_accuracy: 0.6667 - val_loss: 0.6193
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5577 - val_accuracy: 0.6667 - val_loss: 0.6189
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5559 - val_accuracy: 0.6667 - val_loss: 0.6184
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5558 - val_accuracy: 0.6667 - val_loss: 0.6179
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5541 - val_accuracy: 0.6667 - val_loss: 0.6174
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5531 - val_accuracy: 0.6667 - val_loss: 0.6169
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5528 - val_accuracy: 0.6667 - val_loss: 0.6164

In [21]:
from tensorflow.keras import optimizers

In [22]:
opt = optimizers.SGD(learning_rate=0.01,momentum=0.9)